"""Initial schema

Revision ID: c8dfe8103cc0
Revises: 
Create Date: 2026-05-24 22:42:30.929012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8dfe8103cc0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_table('analysis_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('video_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_jobs_id'), 'analysis_jobs', ['id'], unique=False)
    op.create_table('processed_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('frame', sa.Integer(), nullable=True),
    sa.Column('time_ms', sa.Float(), nullable=True),
    sa.Column('com_x', sa.Float(), nullable=True),
    sa.Column('com_y', sa.Float(), nullable=True),
    sa.Column('c7_x', sa.Float(), nullable=True),
    sa.Column('c7_y', sa.Float(), nullable=True),
    sa.Column('mid_foot_x', sa.Float(), nullable=True),
    sa.Column('view_type', sa.String(), nullable=True),
    sa.Column('has_barbell', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_results_frame'), 'processed_results', ['frame'], unique=False)
    op.create_index(op.f('ix_processed_results_id'), 'processed_results', ['id'], unique=False)
    op.create_index(op.f('ix_processed_results_job_id'), 'processed_results', ['job_id'], unique=False)
    op.create_table('raw_data',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('frame', sa.Integer(), nullable=True),
    sa.Column('time_ms', sa.Float(), nullable=True),
    sa.Column('landmarks_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_data_frame'), 'raw_data', ['frame'], unique=False)
    op.create_index(op.f('ix_raw_data_id'), 'raw_data', ['id'], unique=False)
    op.create_index(op.f('ix_raw_data_job_id'), 'raw_data', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_data_job_id'), table_name='raw_data')
    op.drop_index(op.f('ix_raw_data_id'), table_name='raw_data')
    op.drop_index(op.f('ix_raw_data_frame'), table_name='raw_data')
    op.drop_table('raw_data')
    op.drop_index(op.f('ix_processed_results_job_id'), table_name='processed_results')
    op.drop_index(op.f('ix_processed_results_id'), table_name='processed_results')
    op.drop_index(op.f('ix_processed_results_frame'), table_name='processed_results')
    op.drop_table('processed_results')
    op.drop_index(op.f('ix_analysis_jobs_id'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
